# Generated by Django 4.0 on 2024-04-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_news_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('Dr', 'Draft'), ('Pb', 'Published')], default='Dr', max_length=2),
        ),
    ]
