# Generated by Django 4.0 on 2024-04-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_alter_news_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='images',
            new_name='image',
        ),
    ]
