# Generated by Django 4.0 on 2024-04-23 09:15

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_contact'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='news',
            managers=[
                ('pulished', django.db.models.manager.Manager()),
            ],
        ),
    ]
