# Generated by Django 4.0 on 2024-04-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_alter_news_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PHOTOGRAPHY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/images/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_time']},
        ),
    ]
